kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cks
featureGates:
  # any feature gate can be enabled here with "Name": true
  # or disabled here with "Name": false
  # not all feature gates are tested, however
  "CSIMigration": true
networking:
  apiServerAddress: "0.0.0.0"
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 36443
  podSubnet: "10.100.0.0/16"
  serviceSubnet: "10.200.0.0/16"
  # the default CNI will not be installed
  disableDefaultCNI: true
  kubeProxyMode: "ipvs"
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."harbor.kengdie.xyz"]
    endpoint = ["http://harbor.kengdie.xyz"]
nodes:
- role: control-plane
  image: harbor.kengdie.xyz/k8s/kindest/node:v1.24.0
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
        certSANs:
        - "cks.kengdie.xyz"
        - "127.0.0.1"
        - "localhost"
        - "0.0.0.0"
        extraArgs:
          service-node-port-range: "30000-40000"
          enable-admission-plugins: "NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
          enable-aggregator-routing: "true"
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
  - containerPort: 38080
    hostPort: 8080
  - containerPort: 30443
    hostPort: 443
  extraMounts:
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /root/kind/docker-config.json
- role: worker
  image: harbor.kengdie.xyz/k8s/kindest/node:v1.24.0
  extraMounts:
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /root/kind/docker-config.json
- role: worker
  image: harbor.kengdie.xyz/k8s/kindest/node:v1.24.0
  extraMounts:
  - containerPath: /var/lib/kubelet/config.json
    hostPath: /root/kind/docker-config.json
